[book]
title = "Detritus Documentation"
authors = ["Can H. Tartanoglu"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
site-url = "/rs-detritus/"
default-theme = "coal"
preferred-dark-theme = "coal"
git-repository-url = "https://codeberg.org/caniko/rs-detritus"
